### ISSUE TITLE
Crear las entidades de programa

### ISSUE THREAD

**Issue by Ozumas7** [Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1#5]
Crear las clases de programa en el directorio src con los parámetros que se guardan en la base de datos, que se pueden encontrar [aquí](https://github.com/Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1/blob/documentation/programa.sql)

Un ejemplo breve se puede encontrar [aquí](https://github.com/Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1/blob/documentation/ejemploEntidad.md)

Recordad usar el ```namespace EGC\VisPrograma;``` al principio de la clase

**Comment by andsotval** [comment]
#5 Finalizar identidades

Finalizar identidades

closed #5
