### ISSUE TITLE
Crear un adaptador de la base de datos

### ISSUE THREAD

**Issue by Ozumas7** [Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1#7]
Crear un adaptador para la base de datos y que obtenga los distintos datos de la base de datos y lo transforme a las entidades.

**Comment by Ozumas7** [comment]
Creada otra incidencia relacionada con esta y mas especifica [#19](https://github.com/Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1/issues/19)

**Comment by andsotval** [comment]
Creada otra incidencia relacionada con esta y mas especifica [#19](https://github.com/Proyecto-EGC-G1/VisualizacionPrograma-EGC-G1/issues/19)
